version: '3.9'

services:
  kb:
    # build: ./configs/neo4j/.
    image: neo4j:5.18-community
    restart: always
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/PHM0987654321
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
